[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "Analytics Microservice V2"
internalPort = 8000

[env]
# Service configuration
SERVICE_NAME = "analytics-microservice-v2"
DEBUG_MODE = "false"
LOG_LEVEL = "INFO"

# LLM configuration (set in Railway dashboard)
LLM_PROVIDER = "gemini"
# GOOGLE_API_KEY = "${{GOOGLE_API_KEY}}"

# Analytics configuration
ENABLE_SYNTHETIC_DATA = "true"
ENABLE_LLM_ENHANCEMENT = "true"
DEFAULT_THEME = "modern"
MAX_DATA_POINTS = "10000"

# Rate limiting
RATE_LIMIT_ENABLED = "true"
RATE_LIMIT_REQUESTS = "60"
RATE_LIMIT_WINDOW = "60"

# WebSocket configuration
WS_TIMEOUT = "300"
MAX_CONNECTIONS = "100"

# CORS configuration
CORS_ORIGINS = "*"

# Monitoring
ENABLE_METRICS = "true"